services:

  appDatabaseSql: 
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - appDatabase:/var/lib/mysql
      - ./back-end/db/:/docker-entrypoint-initdb.d
    expose: 
      - 3306
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqlDatabase
    networks: 
      - back
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    
  serverBack:
    image: node:18-alpine
    ports: 
      - 8080:8080
    depends_on: 
      appDatabaseSql:
        condition: service_healthy
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mysqlDatabase 
    working_dir: /back-end
    volumes: 
      - ./back-end:/back-end
    command: sh -c "npm install && npm start"
    networks:
      - back

  frontApp:
    image: node:18-alpine
    ports: 
      - 3000:3000 
    working_dir: /front-end
    volumes: 
      - ./front-end/excuses-project:/front-end
    command: sh -c "npm install && npm start"
    networks:
      - back

volumes: 
  appDatabase: 

networks: 
  back: 
    driver: bridge