services:

  appDatabaseSql: 
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - appDatabase:/var/lib/mysql
      - ./back-end/db/:/docker-entrypoint-initdb.d
    expose: 
      - 3306
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqlDatabase
    networks: 
      - back-end
    
  serverBack:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    depends_on: 
      - appDatabaseSql
    ports: 
      - 3001:3001
    working_dir: /back-end
    volumes: 
      - ./back-end:/back-end
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mysqlDatabase 
    networks:
      - back-end 

volumes: 
  appDatabase: 

networks: 
  back-end: 
    driver: bridge